name: "Podcast Generator Linkedin-Course-Practice"
author: "Samir Bhattarai"
description: "Generaes a feed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: Generates a feed for a podcast from a YAML file
    rewuired: true
    default: $({ github.actor })@localhost
  name:
    description: The committer's name
    required: true
    default: ${{ github.actor }}
